apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ template "navigator.fullname" . }}
  labels:
    app: {{ template "navigator.name" . }}
    chart: {{ template "navigator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: {{ template "navigator.fullname" . }}
  namespace: {{ .Release.Namespace }}
