{{- $apiDefault := randAlphaNum 16 -}}
{{- $basicDefault := randAlphaNum 16 -}}
{{- $jwtDefault := randAlphaNum 16 -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "navigator.fullname" . }}-creds
  labels:
    app: {{ template "navigator.name" . }}
    chart: {{ template "navigator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  apiKey: {{ default $apiDefault .Values.auth.api.key | b64enc | quote }}
  basicPassword: {{ default $basicDefault .Values.auth.basic.password | b64enc | quote }}
  jwtSecret: {{ default $jwtDefault .Values.auth.jwt.secret | b64enc | quote }}
