apiVersion: v1
kind: Secret
metadata:
  name: {{ template "navigator.fullname" . }}-kubeconfigs
  labels:
    app: {{ template "navigator.name" . }}
    chart: {{ template "navigator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.kubeconfigs }}
data:
{{ toYaml . | indent 2 }}
{{- end }}
