export PATH := $(PATH):node_modules/.bin/

install:
	yarn install
.PHONY: install

start:
	react-scripts start
.PHONY: start

build:
	react-scripts build
.PHONY: build

test:
	react-scripts build
.PHONY: test

clean:
	rm -rf node_modules build
.PHONY: clean
