#!/bin/bash

# Copy over from the read-only filesystem.
mkdir /etc/kubeconfig
cp -r /etc/ro/kubeconfig /etc/kubeconfig

# Setup the default service account as a 'default' cluster if desired.
if [ "$DEFAULT_SERVICE_ACCOUNT" = "true" ]; then

CA=$(cat /var/run/secrets/kubernetes.io/serviceaccount/ca.crt | base64 | tr -d '\n')
TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)

cat > /etc/kubeconfig/config <<EOF
apiVersion: v1
kind: Config
current-context: default
clusters:
- name: default
  cluster:
    server: https://${KUBERNETES_SERVICE_HOST}
    certificate-authority-data: ${CA}
users:
- name: default
  user:
    token: ${TOKEN}
contexts:
- name: default
  context:
    cluster: default
    user: default
EOF

fi

# Setup git credentials.
if [ "$GIT_CREDENTIALS" != "" ]; then
cat > $HOME/.gitconfig <<EOF
[credential]
	helper = store
EOF
echo $GIT_CREDENTIALS > $HOME/.git-credentials
fi

export NODE_ENV=production
exec node index.js
