source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end


gem 'rails',          '5.1.6'
gem 'pg'
gem 'puma',           '3.12.0'
gem 'uglifier',       '4.1.19'
gem 'turbolinks',     '5.2.0'
gem 'dry-validation', github: 'dry-rb/dry-validation'
gem 'tzinfo-data',    '1.2018.5'
gem 'web-console',    group: :development
gem 'delayed_job_active_record'
gem 'lograge'
